name: Actualitzar Mapa Strava
on:
  schedule:
    - cron: '0 21 * * *' # S'executa cada dia a les 22h (hora espanyola aprox)
  workflow_dispatch: # Permet executar-lo a mà des de GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codi
        uses: actions/checkout@v3

      - name: Instal·lar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instal·lar llibreries
        run: pip install requests polyline

      - name: Executar script de Python
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
        run: python update_map.py

     - name: Pujar canvis al JSON
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add dades_ruta.json
          git pull --rebase origin main  # Aquesta línia és la clau!
          git commit -m "Actualització automàtica de la ruta" || echo "No hi ha canvis per pujar"
          git push
